before_script:
  # - npm install -g gulp

language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "node"

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
